#!/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be executed as root" 1>&2
   exit 1
fi
HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs
setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX app/cache app/logs
echo "Permissions for  app/cache and app/logs were successfully modified!"
exit 0
