imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: %use_assetic_controller%

#swiftmailer:
#    delivery_address: me@example.com

bazinga_faker:
    orm: doctrine
    locale: pt_BR
    entities:
        Dcw\GestaoBundle\Entity\Address:
            number: 10
            custom_formatters:
                address: { method: streetName }
                complement: { method: secondaryAddress }
                neighborhood: { method: name }
                number: { method: buildingNumber }
                city: { method: city }
                state: { method: stateAbbr }
                zipcode: { method: numerify, parameters: [ "##.###-###" ] }
        Dcw\GestaoBundle\Entity\Store:
            number: 10
            custom_formatters:
                name: { method: company }
                cnpj: { method: numerify, parameters: [ "##.###.###/####-##" ] }
        Dcw\GestaoBundle\Entity\Invoice:
            number: 10
            custom_formatters:
                value: { method: randomFloat }
                date: { method: date, parameters: [ "d/m/Y" ] }
                time: { method: time, parameters: [ "H:i" ] }
        Dcw\GestaoBundle\Entity\Tag:
            number: 5
            custom_formatters:
                name: { method: randomElement, parameters: [ [ 'lazer', 'alimentação', 'vestuário', 'saúde' ] ] }
