Dcw\GestaoBundle\Entity\InvoiceTag:
# table config
    type: entity
    table: invoice_tag
    repositoryClass: Dcw\GestaoBundle\Repository\InvoiceTagRepository
# pk
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
# other fields
    oneToOne:
        # invoice relationship
        invoice:
            targetEntity: Invoice

        # tag relationship
        tag:
            targetEntity: Tag
