NAW\KodingBundle\Entity\QuestionAlternative:
# table config
    type: entity
    table: question_alternative
    repositoryClass: NAW\KodingBundle\Repository\QuestionAlternativeRepository
# pk
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
# other fields
    fields:
        text:
            type: text
            nullable: false
        correct_answer:
            type: boolean
            nullable: true
# associations
    manyToOne:
        question:
            targetEntity: Question
            inversedBy: alternatives
