NAW\KodingBundle\Entity\Question:
# table config
    type: entity
    table: question
    repositoryClass: NAW\KodingBundle\Repository\QuestionRepository
# pk    
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
# other fields
    fields:
        text:
            type: text
            nullable: false
# associations
    oneToMany:
        alternatives:
            targetEntity: QuestionAlternative
            mappedBy: question
