<?php

namespace Dcw\GestaoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceTagRepository extends EntityRepository
{
}
